// Starter catalogue. Facts are public (titles, years, credits); the emoji clues are our own.
// Before launch, re-check every row against Wikidata and move day-to-day edits to an admin page.

export const PEOPLE: Record<string, { en: string; te: string }> = {
  // Directors
  rajamouli: { en: "S. S. Rajamouli", te: "ఎస్. ఎస్. రాజమౌళి" },
  sukumar: { en: "Sukumar", te: "సుకుమార్" },
  trivikram: { en: "Trivikram Srinivas", te: "త్రివిక్రమ్ శ్రీనివాస్" },
  puri: { en: "Puri Jagannadh", te: "పూరి జగన్నాథ్" },
  koratala: { en: "Koratala Siva", te: "కొరటాల శివ" },
  gunasekhar: { en: "Gunasekhar", te: "గుణశేఖర్" },
  "sandeep-vanga": { en: "Sandeep Reddy Vanga", te: "సందీప్ రెడ్డి వంగా" },
  gowtam: { en: "Gowtam Tinnanuri", te: "గౌతమ్ తిన్ననూరి" },
  "nag-ashwin": { en: "Nag Ashwin", te: "నాగ్ అశ్విన్" },
  "prashanth-neel": { en: "Prashanth Neel", te: "ప్రశాంత్ నీల్" },
  "hanu-raghavapudi": { en: "Hanu Raghavapudi", te: "హను రాఘవపూడి" },
  "sekhar-kammula": { en: "Sekhar Kammula", te: "శేఖర్ కమ్ముల" },
  parasuram: { en: "Parasuram", te: "పరశురామ్" },
  "harish-shankar": { en: "Harish Shankar", te: "హరీష్ శంకర్" },
  "sj-surya": { en: "S. J. Surya", te: "ఎస్. జె. సూర్య" },
  "b-gopal": { en: "B. Gopal", te: "బి. గోపాల్" },
  vinayak: { en: "V. V. Vinayak", te: "వి. వి. వినాయక్" },
  "bommarillu-bhaskar": { en: "Bhaskar", te: "భాస్కర్" },
  "vikram-kumar": { en: "Vikram Kumar", te: "విక్రమ్ కుమార్" },
  rgv: { en: "Ram Gopal Varma", te: "రామ్ గోపాల్ వర్మ" },
  "kv-reddy": { en: "K. V. Reddy", te: "కె. వి. రెడ్డి" },
  viswanath: { en: "K. Viswanath", te: "కె. విశ్వనాథ్" },
  "raghavendra-rao": { en: "K. Raghavendra Rao", te: "కె. రాఘవేంద్రరావు" },
  "gautham-menon": { en: "Gautham Vasudev Menon", te: "గౌతమ్ వాసుదేవ్ మేనన్" },
  sobhan: { en: "Sobhan", te: "శోభన్" },
  "srinu-vaitla": { en: "Srinu Vaitla", te: "శ్రీను వైట్ల" },
  "surender-reddy": { en: "Surender Reddy", te: "సురేందర్ రెడ్డి" },
  boyapati: { en: "Boyapati Srinu", te: "బోయపాటి శ్రీను" },
  "vijaya-bhaskar": { en: "K. Vijaya Bhaskar", te: "కె. విజయ భాస్కర్" },
  "anil-ravipudi": { en: "Anil Ravipudi", te: "అనిల్ రావిపూడి" },
  "tharun-bhascker": { en: "Tharun Bhascker", te: "తరుణ్ భాస్కర్" },
  "ravikanth-perepu": { en: "Ravikanth Perepu", te: "రవికాంత్ పేరేపు" },
  "sashi-kiran-tikka": { en: "Sashi Kiran Tikka", te: "శశి కిరణ్ తిక్క" },
  "prabhu-deva": { en: "Prabhu Deva", te: "ప్రభుదేవా" },
  "vamshi-paidipally": { en: "Vamshi Paidipally", te: "వంశీ పైడిపల్లి" },

  // Music directors
  keeravani: { en: "M. M. Keeravani", te: "ఎం. ఎం. కీరవాణి" },
  dsp: { en: "Devi Sri Prasad", te: "దేవి శ్రీ ప్రసాద్" },
  thaman: { en: "S. Thaman", te: "ఎస్. తమన్" },
  "mani-sharma": { en: "Mani Sharma", te: "మణిశర్మ" },
  radhan: { en: "Radhan", te: "రధన్" },
  anirudh: { en: "Anirudh Ravichander", te: "అనిరుధ్ రవిచందర్" },
  mickey: { en: "Mickey J. Meyer", te: "మిక్కీ జె. మేయర్" },
  "santhosh-narayanan": { en: "Santhosh Narayanan", te: "సంతోష్ నారాయణన్" },
  "ravi-basrur": { en: "Ravi Basrur", te: "రవి బస్రూర్" },
  "vishal-chandrashekhar": { en: "Vishal Chandrashekhar", te: "విశాల్ చంద్రశేఖర్" },
  shakthikanth: { en: "Shakthikanth Karthick", te: "శక్తికాంత్ కార్తీక్" },
  "gopi-sundar": { en: "Gopi Sundar", te: "గోపీ సుందర్" },
  "anup-rubens": { en: "Anup Rubens", te: "అనూప్ రూబెన్స్" },
  ilaiyaraaja: { en: "Ilaiyaraaja", te: "ఇళయరాజా" },
  ghantasala: { en: "Ghantasala", te: "ఘంటసాల" },
  "kv-mahadevan": { en: "K. V. Mahadevan", te: "కె. వి. మహదేవన్" },
  "ar-rahman": { en: "A. R. Rahman", te: "ఏ. ఆర్. రెహమాన్" },
  koti: { en: "Koti", te: "కోటి" },
  bheems: { en: "Bheems Ceciroleo", te: "భీమ్స్ సిసిరోలియో" },
  "vivek-sagar": { en: "Vivek Sagar", te: "వివేక్ సాగర్" },
  "sricharan-pakala": { en: "Sricharan Pakala", te: "శ్రీచరణ్ పాకాల" },

  // Actors
  prabhas: { en: "Prabhas", te: "ప్రభాస్" },
  "allu-arjun": { en: "Allu Arjun", te: "అల్లు అర్జున్" },
  "ram-charan": { en: "Ram Charan", te: "రామ్ చరణ్" },
  "ntr-jr": { en: "N. T. Rama Rao Jr.", te: "జూనియర్ ఎన్టీఆర్" },
  nani: { en: "Nani", te: "నాని" },
  "vijay-deverakonda": { en: "Vijay Deverakonda", te: "విజయ్ దేవరకొండ" },
  "mahesh-babu": { en: "Mahesh Babu", te: "మహేష్ బాబు" },
  "keerthy-suresh": { en: "Keerthy Suresh", te: "కీర్తి సురేష్" },
  "dulquer-salmaan": { en: "Dulquer Salmaan", te: "దుల్కర్ సల్మాన్" },
  "varun-tej": { en: "Varun Tej", te: "వరుణ్ తేజ్" },
  "pawan-kalyan": { en: "Pawan Kalyan", te: "పవన్ కళ్యాణ్" },
  chiranjeevi: { en: "Chiranjeevi", te: "చిరంజీవి" },
  siddharth: { en: "Siddharth", te: "సిద్ధార్థ్" },
  "varun-sandesh": { en: "Varun Sandesh", te: "వరుణ్ సందేశ్" },
  nagarjuna: { en: "Nagarjuna", te: "నాగార్జున" },
  "naga-chaitanya": { en: "Naga Chaitanya", te: "నాగ చైతన్య" },
  ntr: { en: "N. T. Rama Rao", te: "ఎన్. టి. రామారావు" },
  anr: { en: "Akkineni Nageswara Rao", te: "అక్కినేని నాగేశ్వరరావు" },
  somayajulu: { en: "J. V. Somayajulu", te: "జె. వి. సోమయాజులు" },
  balakrishna: { en: "Nandamuri Balakrishna", te: "నందమూరి బాలకృష్ణ" },
  venkatesh: { en: "Venkatesh", te: "వెంకటేష్" },
  "adivi-sesh": { en: "Adivi Sesh", te: "అడివి శేష్" },
  karthi: { en: "Karthi", te: "కార్తి" },
  sudeep: { en: "Sudeep", te: "సుదీప్" },
  mohanlal: { en: "Mohanlal", te: "మోహన్‌లాల్" },
  sridevi: { en: "Sridevi", te: "శ్రీదేవి" },
  samantha: { en: "Samantha", te: "సమంత" },
  "sai-pallavi": { en: "Sai Pallavi", te: "సాయి పల్లవి" },
  "rashmika-mandanna": { en: "Rashmika Mandanna", te: "రష్మిక మందన్న" },
};

type SeedMovie = {
  slug: string;
  en: string;
  te: string;
  year: number;
  director: string;
  music: string;
  leads: string[];
  emoji: string;
};

export const MOVIES: SeedMovie[] = [
  { slug: "baahubali-the-beginning", en: "Baahubali: The Beginning", te: "బాహుబలి: ది బిగినింగ్", year: 2015, director: "rajamouli", music: "keeravani", leads: ["prabhas"], emoji: "👶🌊🏔️⚔️👑" },
  { slug: "baahubali-2-the-conclusion", en: "Baahubali 2: The Conclusion", te: "బాహుబలి 2: ది కన్‌క్లూజన్", year: 2017, director: "rajamouli", music: "keeravani", leads: ["prabhas"], emoji: "❓🗡️🧔👑🐘" },
  { slug: "rrr", en: "RRR", te: "ఆర్ఆర్ఆర్", year: 2022, director: "rajamouli", music: "keeravani", leads: ["ntr-jr", "ram-charan"], emoji: "🔥💧🐅🏍️🇮🇳" },
  { slug: "magadheera", en: "Magadheera", te: "మగధీర", year: 2009, director: "rajamouli", music: "keeravani", leads: ["ram-charan"], emoji: "🐎⚔️🔁💞🏰" },
  { slug: "eega", en: "Eega", te: "ఈగ", year: 2012, director: "rajamouli", music: "keeravani", leads: ["nani", "sudeep"], emoji: "🪰💔🔪😤" },
  { slug: "chatrapathi", en: "Chatrapathi", te: "ఛత్రపతి", year: 2005, director: "rajamouli", music: "keeravani", leads: ["prabhas"], emoji: "🚢👩‍👦🦈👊" },
  { slug: "simhadri", en: "Simhadri", te: "సింహాద్రి", year: 2003, director: "rajamouli", music: "keeravani", leads: ["ntr-jr"], emoji: "🦁🌴🇮🇳🔪" },
  { slug: "pushpa-the-rise", en: "Pushpa: The Rise", te: "పుష్ప: ది రైజ్", year: 2021, director: "sukumar", music: "dsp", leads: ["allu-arjun", "rashmika-mandanna"], emoji: "🌲🪵🚚🫳🔥" },
  { slug: "pushpa-2-the-rule", en: "Pushpa 2: The Rule", te: "పుష్ప 2: ది రూల్", year: 2024, director: "sukumar", music: "dsp", leads: ["allu-arjun", "rashmika-mandanna"], emoji: "🪵👑🥻🔥🚁" },
  { slug: "rangasthalam", en: "Rangasthalam", te: "రంగస్థలం", year: 2018, director: "sukumar", music: "dsp", leads: ["ram-charan", "samantha"], emoji: "👂🗳️🏘️🐍" },
  { slug: "arya", en: "Arya", te: "ఆర్య", year: 2004, director: "sukumar", music: "dsp", leads: ["allu-arjun"], emoji: "💘🙋‍♂️💔😎" },
  { slug: "ala-vaikunthapurramuloo", en: "Ala Vaikunthapurramuloo", te: "అల వైకుంఠపురములో", year: 2020, director: "trivikram", music: "thaman", leads: ["allu-arjun"], emoji: "👶🔄🏠🏢💃" },
  { slug: "athadu", en: "Athadu", te: "అతడు", year: 2005, director: "trivikram", music: "mani-sharma", leads: ["mahesh-babu"], emoji: "🎯🚂🏡🎭" },
  { slug: "attarintiki-daredi", en: "Attarintiki Daredi", te: "అత్తారింటికి దారేది", year: 2013, director: "trivikram", music: "dsp", leads: ["pawan-kalyan", "samantha"], emoji: "✈️👵🏠🚗❤️" },
  { slug: "pokiri", en: "Pokiri", te: "పోకిరి", year: 2006, director: "puri", music: "mani-sharma", leads: ["mahesh-babu"], emoji: "😎🔫👮🎬" },
  { slug: "temper", en: "Temper", te: "టెంపర్", year: 2015, director: "puri", music: "anup-rubens", leads: ["ntr-jr"], emoji: "👮💰😈➡️😇" },
  { slug: "srimanthudu", en: "Srimanthudu", te: "శ్రీమంతుడు", year: 2015, director: "koratala", music: "dsp", leads: ["mahesh-babu"], emoji: "💰🏘️🚲🤝" },
  { slug: "mirchi", en: "Mirchi", te: "మిర్చి", year: 2013, director: "koratala", music: "dsp", leads: ["prabhas"], emoji: "🌶️🏘️🕊️👊" },
  { slug: "janatha-garage", en: "Janatha Garage", te: "జనతా గ్యారేజ్", year: 2016, director: "koratala", music: "dsp", leads: ["ntr-jr", "mohanlal"], emoji: "🔧🌳🏙️🤝" },
  { slug: "devara-part-1", en: "Devara: Part 1", te: "దేవర: పార్ట్ 1", year: 2024, director: "koratala", music: "anirudh", leads: ["ntr-jr"], emoji: "🌊🚤🦈🗡️" },
  { slug: "okkadu", en: "Okkadu", te: "ఒక్కడు", year: 2003, director: "gunasekhar", music: "mani-sharma", leads: ["mahesh-babu"], emoji: "🤼🏛️👧🏃" },
  { slug: "arjun-reddy", en: "Arjun Reddy", te: "అర్జున్ రెడ్డి", year: 2017, director: "sandeep-vanga", music: "radhan", leads: ["vijay-deverakonda"], emoji: "🩺💔🍾🧔" },
  { slug: "jersey", en: "Jersey", te: "జెర్సీ", year: 2019, director: "gowtam", music: "anirudh", leads: ["nani"], emoji: "🏏👕👦🚂" },
  { slug: "mahanati", en: "Mahanati", te: "మహానటి", year: 2018, director: "nag-ashwin", music: "mickey", leads: ["keerthy-suresh", "dulquer-salmaan"], emoji: "🎬👑👩📰" },
  { slug: "kalki-2898-ad", en: "Kalki 2898 AD", te: "కల్కి 2898 ఏ.డి", year: 2024, director: "nag-ashwin", music: "santhosh-narayanan", leads: ["prabhas"], emoji: "🚀🏜️🤰🏹" },
  { slug: "salaar-part-1-ceasefire", en: "Salaar: Part 1 – Ceasefire", te: "సలార్: పార్ట్ 1 – సీజ్‌ఫైర్", year: 2023, director: "prashanth-neel", music: "ravi-basrur", leads: ["prabhas"], emoji: "🤝🏰🩸🦖" },
  { slug: "sita-ramam", en: "Sita Ramam", te: "సీతా రామం", year: 2022, director: "hanu-raghavapudi", music: "vishal-chandrashekhar", leads: ["dulquer-salmaan"], emoji: "✉️🪖❄️💌" },
  { slug: "fidaa", en: "Fidaa", te: "ఫిదా", year: 2017, director: "sekhar-kammula", music: "shakthikanth", leads: ["varun-tej", "sai-pallavi"], emoji: "🇺🇸👨‍⚕️🌾💃" },
  { slug: "happy-days", en: "Happy Days", te: "హ్యాపీ డేస్", year: 2007, director: "sekhar-kammula", music: "mickey", leads: ["varun-sandesh"], emoji: "🎓🏫👫👫🚌" },
  { slug: "geetha-govindam", en: "Geetha Govindam", te: "గీత గోవిందం", year: 2018, director: "parasuram", music: "gopi-sundar", leads: ["vijay-deverakonda", "rashmika-mandanna"], emoji: "🚌📱😳🙏💍" },
  { slug: "gabbar-singh", en: "Gabbar Singh", te: "గబ్బర్ సింగ్", year: 2012, director: "harish-shankar", music: "dsp", leads: ["pawan-kalyan"], emoji: "👮🤠🏘️🥊" },
  { slug: "kushi", en: "Kushi", te: "ఖుషి", year: 2001, director: "sj-surya", music: "mani-sharma", leads: ["pawan-kalyan"], emoji: "😤💘🏫🤐" },
  { slug: "indra", en: "Indra", te: "ఇంద్ర", year: 2002, director: "b-gopal", music: "mani-sharma", leads: ["chiranjeevi"], emoji: "🚕🏔️🕉️💧👑" },
  { slug: "samarasimha-reddy", en: "Samarasimha Reddy", te: "సమరసింహా రెడ్డి", year: 1999, director: "b-gopal", music: "mani-sharma", leads: ["balakrishna"], emoji: "🦁🔪🏨👨‍👧" },
  { slug: "tagore", en: "Tagore", te: "ఠాగూర్", year: 2003, director: "vinayak", music: "mani-sharma", leads: ["chiranjeevi"], emoji: "👨‍🏫📋⚖️🕵️" },
  { slug: "bommarillu", en: "Bommarillu", te: "బొమ్మరిల్లు", year: 2006, director: "bommarillu-bhaskar", music: "dsp", leads: ["siddharth"], emoji: "👨‍👦🏠🚦😅" },
  { slug: "manam", en: "Manam", te: "మనం", year: 2014, director: "vikram-kumar", music: "anup-rubens", leads: ["anr", "nagarjuna", "naga-chaitanya"], emoji: "👴👨👦🔁💞" },
  { slug: "shiva", en: "Shiva", te: "శివ", year: 1989, director: "rgv", music: "ilaiyaraaja", leads: ["nagarjuna"], emoji: "🚲⛓️🎓👊" },
  { slug: "mayabazar", en: "Mayabazar", te: "మాయాబజార్", year: 1957, director: "kv-reddy", music: "ghantasala", leads: ["ntr", "anr"], emoji: "🪄🍲👑💍" },
  { slug: "sankarabharanam", en: "Sankarabharanam", te: "శంకరాభరణం", year: 1980, director: "viswanath", music: "kv-mahadevan", leads: ["somayajulu"], emoji: "🎶🪕🙏🌊" },
  { slug: "jagadeka-veerudu-athiloka-sundari", en: "Jagadeka Veerudu Athiloka Sundari", te: "జగదేక వీరుడు అతిలోక సుందరి", year: 1990, director: "raghavendra-rao", music: "ilaiyaraaja", leads: ["chiranjeevi", "sridevi"], emoji: "💍✨👸🧚🏝️" },
  { slug: "ye-maaya-chesave", en: "Ye Maaya Chesave", te: "ఏ మాయ చేసావే", year: 2010, director: "gautham-menon", music: "ar-rahman", leads: ["naga-chaitanya", "samantha"], emoji: "🎬💕🏠⛪🎵" },
  { slug: "varsham", en: "Varsham", te: "వర్షం", year: 2004, director: "sobhan", music: "dsp", leads: ["prabhas"], emoji: "🌧️💃☔💞" },
  { slug: "dookudu", en: "Dookudu", te: "దూకుడు", year: 2011, director: "srinu-vaitla", music: "thaman", leads: ["mahesh-babu"], emoji: "👮🎭🏛️😂" },
  { slug: "race-gurram", en: "Race Gurram", te: "రేసుగుర్రం", year: 2014, director: "surender-reddy", music: "thaman", leads: ["allu-arjun"], emoji: "🐎👬👮🗳️" },
  { slug: "akhanda", en: "Akhanda", te: "అఖండ", year: 2021, director: "boyapati", music: "thaman", leads: ["balakrishna"], emoji: "🔱🧘👬🔥" },
  { slug: "nuvvu-naaku-nachav", en: "Nuvvu Naaku Nachav", te: "నువ్వు నాకు నచ్చావ్", year: 2001, director: "vijaya-bhaskar", music: "koti", leads: ["venkatesh"], emoji: "🏠🤝💘😂" },
  { slug: "sankranthiki-vasthunam", en: "Sankranthiki Vasthunam", te: "సంక్రాంతికి వస్తున్నాం", year: 2025, director: "anil-ravipudi", music: "bheems", leads: ["venkatesh"], emoji: "🪁👮👩‍❤️‍👨👩🏘️" },
  { slug: "pelli-choopulu", en: "Pelli Choopulu", te: "పెళ్లి చూపులు", year: 2016, director: "tharun-bhascker", music: "vivek-sagar", leads: ["vijay-deverakonda"], emoji: "💍🚚🍔👩‍🍳" },
  { slug: "kshanam", en: "Kshanam", te: "క్షణం", year: 2016, director: "ravikanth-perepu", music: "sricharan-pakala", leads: ["adivi-sesh"], emoji: "👧❓🕵️🇺🇸" },
  { slug: "major", en: "Major", te: "మేజర్", year: 2022, director: "sashi-kiran-tikka", music: "sricharan-pakala", leads: ["adivi-sesh"], emoji: "🪖🏨🔥🇮🇳" },
  { slug: "nuvvostanante-nenoddantana", en: "Nuvvostanante Nenoddantana", te: "నువ్వొస్తానంటే నేనొద్దంటానా", year: 2005, director: "prabhu-deva", music: "dsp", leads: ["siddharth"], emoji: "🌾🐄💪💞" },
  { slug: "oopiri", en: "Oopiri", te: "ఊపిరి", year: 2016, director: "vamshi-paidipally", music: "gopi-sundar", leads: ["nagarjuna", "karthi"], emoji: "♿🤝🎨🪂" },
];
